FROM python:3.11

# The postgresql-client is included here for dev psql
RUN apt-get update && \
        apt-get install -y postgresql-client && \
        rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip

WORKDIR /build
COPY req-wheels /build/wheels/
COPY requirements.txt /build/raton/
COPY setup.py /build/raton/
COPY raton /build/raton/raton/

WORKDIR /build/raton
RUN pip install -r requirements.txt --no-index --find-links=/build/wheels
RUN pip install -e .

EXPOSE 8000

ENTRYPOINT ["uvicorn", "raton.starter:app", "--host=0.0.0.0"]
